### ISSUE TITLE
[spike]: look into linking with lld

### ISSUE THREAD

**Issue by dr-bonez** [Start9Labs/embassy-os#1000]
https://nnethercote.github.io/perf-book/compile-times.html suggests we can reduce compile times by linking with lld instead of gcc. a cursory glance indicates its instability is mainly to do with windows, which we do not need to support, however if there are issues even on linux, this is not viable.

**Comment by Blu-J** [comment]
From the research, the linux + this linker don't have issues. Just Mac, sometimes Windows

As for speed benefits, 1:45 with or without this option, so not sure if it matters

**Comment by chrisguida** [comment]
The link step took super long in an ubuntu VM on my Mac. Will test to see if lld speeds things up

**Comment by Blu-J** [comment]
This is the only thing saving me time on the builds, it is saving me 30-40 seconds on the build time, so that is almost a 30% faster build times, but only on subsequent builds

```toml

[profile.release]
incremental = true
```

**Comment by Blu-J** [comment]
And with the following got the build time down to 1:10 
```toml

[build]
rustflags = ["-C", "linker=clang", "-C", "link-arg=-fuse-ld=lld"]

[profile.release]
incremental = true
```
