### ISSUE TITLE
[feat]: CI Build Checking/Testing

### ISSUE THREAD

**Issue by ProofOfKeags** [Start9Labs/embassy-os#1032]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature, without success.

### Describe the Feature Request

CI Build/Testing

### Describe the Use Case

I'd like to get automated build verification onto the branch checks of PR's into the mainline. This would save us from accidentally merging broken builds to master or other protected branches

### Describe Preferred Solution

Travis CI

### Describe Alternatives

Circle CI
Jenkins 😬

**Comment by moerketh** [comment]
Would you consider a GitHub Actions workflow?

A basic workflow using the existing scripts would cover your use case with little effort. This can be iterated on to make it faster and more complete. For example:

```yaml
name: Build Pipeline

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Set up Docker Buildx        
      uses: docker/setup-buildx-action@v1
    
    - name: Build
      run: make
```

This runs the build using the default software installed on the GitHub ubuntu-latest environment, see [here](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md).
