### ISSUE TITLE
[feat]: List of objects not displaying properly in config

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/embassy-os#1347]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem, without success.

### EmbassyOS Version

72cb451f5a4be02ad651e2c0bf4973dd8f36f9b1

### Device

Laptop/Desktop

### Device OS

Linux

### Device OS Version

Ubuntu 20.04

### Browser

Firefox

### Browser Version

98.0.1

### Current Behavior

This config spec:

```
        addnode:
          name: Add Nodes
          description: Add addresses of nodes to connect to.
          type: list
          subtype: object
          range: "[0,*)"
          default: []
          spec:
            type: object
            nullable: false
            name: "Peer"
            description: "Peer to connect to"
            spec:
              hostname:
                type: string
                nullable: false
                name: "Hostname"
                description: "Domain or IP address of bitcoin peer"
                masked: true
                pattern: "(^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$)|((^(([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([0-9a-fA-F]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]))$)|(^[a-z2-7]{16}\\.onion$)|(^([a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?\\.)+[a-z0-9][a-z0-9-]{0,61}[a-z0-9]$))"
                pattern-description: Must be either a domain name, or an IPv4 or IPv6 address. Do not include protocol scheme (eg 'http://') or port.
              port:
                type: number
                # nullable: false
                nullable: true
                name: "Port"
                description: "Port that peer is listening on for inbound p2p connections"
                # default: 8333
                range: "[0,65535]"
                integral: true
```

Renders like this:

![Screenshot from 2022-03-18 16-21-05](https://user-images.githubusercontent.com/7445670/159096594-92cf6b06-9538-4292-add9-79ee1386ab0c.png)

### Expected Behavior

The user should be able to see the port field. The port is inaccessible no matter what I do.

### Steps to Reproduce

1. Package s9pk with config spec as above
2. Go to configure it
3. Cannot access second field in object, when object is nested inside a list.

### Anything else?

This is blocking https://github.com/Start9Labs/bitcoind-wrapper/issues/53

**Comment by elvece** [comment]
Looking at the posted config spec, there are some elements that are incorrect for lists of objects. See a working implementation of this type [here](https://github.com/Start9Labs/embassy-pages-wrapper/blob/5e1db3fac4138b591591b096f8f4866e2e54f97e/assets/compat/config_spec.yaml#L44-L53). I recognize that the documentation for this type is wrong and will correct. 

Does the issue persist with those adjustments to the config spec?

**Comment by chrisguida** [comment]
Updated to try:

```
        addnode:
          type: list
          name: Add Nodes
          description: Add addresses of nodes to connect to.
          default: []
          range: "[0,*)"
          # subtype: string
          subtype: object
          spec:
            unique-by: hostname
            display-as: "{{hostname}}"
            spec:
              hostname:
                type: string
                nullable: false
                name: "Hostname"
                description: "Domain or IP address of bitcoin peer"
                masked: true
                pattern: "(^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(:[0-9]{1,5})?$)|((^(([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([0-9a-fA-F]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]))(:[0-9]{1,5})?$)|(^[a-z2-7]{16}\\.onion(:[0-9]{1,5})?$)|(^([a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?\\.)+[a-z0-9][a-z0-9-]{0,61}[a-z0-9](:[0-9]{1,5})?$))"
                pattern-description: Must be either a domain name, or an IPv4 or IPv6 address. Do not include protocol scheme (eg 'http://') or port.
              port:
                type: number
                # nullable: false
                nullable: true
                name: "Port"
                description: "Port that peer is listening on for inbound p2p connections"
                # default: 8333
                range: "[0,65535]"
                integral: true
```

Not seeing any meaningful difference:
![Screenshot from 2022-03-21 17-04-47](https://user-images.githubusercontent.com/7445670/159377385-f46be66f-126a-4588-8b81-ab71a6b89352.png)

Actually now the hostname is covered up, too.
