### ISSUE TITLE
[bug]: health check in dependencies.yaml not fulfulling requirement even when passing

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/embassy-os#1383]
given this `dependencies.yaml` in electrs:

```
bitcoind:
  condition: '''bitcoind.type = "internal-proxy"'
  health_checks: ["synced"]
```

and this health check in bitcoind:
```
health-checks:
  synced:
    name: Synced
    success-message: Bitcoin Core is synced with the network
    type: docker
    image: main
    system: false
    entrypoint: [check-synced.sh](http://check-synced.sh/)
    args: []
    mounts: {}
    io-format: yaml
    inject: true
```

I expect electrs' bitcoind dependency to be fulfilled by a passing `synced` health check. But this is not the case:
<img width="551" alt="Screen Shot 2022-04-05 at 10 28 06 AM" src="https://user-images.githubusercontent.com/7445670/161794876-b6e16188-c939-4cab-b589-8de96789103f.png">
<img width="435" alt="Screen Shot 2022-04-05 at 10 28 24 AM" src="https://user-images.githubusercontent.com/7445670/161794880-850c155f-c56b-4a0e-9887-5a801f632d74.png">
