### ISSUE TITLE
[bug]: Wrong migration running when multiple migrations defined

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/embassy-os#1394]
Steps to reproduce:

1. Create a manifest with this migration section:

```
migrations:
  from:
    "<22.0.0":
      type: docker
      image: main
      system: false
      entrypoint: /usr/local/bin/migrations/lt_22_0_0.sh
      args: ["from"]
      io-format: json
      mounts:
        main: /root/.bitcoin
      inject: false
    "=22.0.0":
      type: docker
      image: main
      system: false
      entrypoint: /usr/local/bin/migrations/eq_22_0_0.sh
      args: ["from"]
      io-format: json
      mounts:
        main: /root/.bitcoin
      inject: false
  to:
    "<22.0.0":
      type: docker
      image: main
      system: false
      entrypoint: /usr/local/bin/migrations/lt_22_0_0.sh
      args: ["to"]
      io-format: json
      mounts:
        main: /root/.bitcoin
      inject: false
    "=22.0.0":
      type: docker
      image: main
      system: false
      entrypoint: /usr/local/bin/migrations/eq_22_0_0.sh
      args: ["to"]
      io-format: json
      mounts:
        main: /root/.bitcoin
      inject: false
```

2. Install 22.0.0
3. Upgrade to 22.0.1
4. Notice that the wrong migration runs:
`Apr 12 16:53:40 embassy-2ef08502 embassyd[1449]: Apr 12 16:53:40.253 TRACE download_install_s9pk{marketplace_url=Some(Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("beta-registry-0-3.start9labs.com")), port: None, path: "/", query: None, fragment: None }) progress=InstallProgress { size: Some(78060336), downloaded: 0, download_complete: false, validated: 0, validation_complete: false, unpacked: 0, unpack_complete: false }}:install_s9pk{pkg_id=PackageId(Id("bitcoind")) version=Version { version: Version(22, 0, 1, 0), string: "22.0.1" } marketplace_url=Some(Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("beta-registry-0-3.start9labs.com")), port: None, path: "/", query: None, fragment: None }) progress=InstallProgress { size: Some(78060336), downloaded: 78060336, download_complete: true, validated: 78060336, validation_complete: false, unpacked: 0, unpack_complete: false }}:execute{self=Docker(DockerAction { image: ImageId(Id("main")), system: false, entrypoint: "/usr/local/bin/migrations/lt_22_0_0.sh", args: ["from"], mounts: {Custom(Id("main")): "/root/.bitcoin"}, io_format: Some(Json), inject: false, shm_size_mb: None, sigterm_timeout: None }) pkg_id=PackageId(Id("bitcoind")) pkg_version=Version { version: Version(22, 0, 1, 0), string: "22.0.1" } name=Some("Migration") volumes=Volumes({Custom(Id("compat")): Assets, Custom(Id("main")): Data { readonly: false }}) allow_inject=false timeout=None}:execute{self=DockerAction { image: ImageId(Id("main")), system: false, entrypoint: "/usr/local/bin/migrations/lt_22_0_0.sh", args: ["from"], mounts: {Custom(Id("main")): "/root/.bitcoin"}, io_format: Some(Json), inject: false, shm_size_mb: None, sigterm_timeout: None } pkg_id=PackageId(Id("bitcoind")) pkg_version=Version { version: Version(22, 0, 1, 0), string: "22.0.1" } name=Some("Migration") volumes=Volumes({Custom(Id("compat")): Assets, Custom(Id("main")): Data { readonly: false }}) allow_inject=false timeout=None}: embassy::action::docker: Command { std: "docker run --rm --network=start9 --add-host=embassy:172.18.0.1 --name bitcoind_Migration.embassy --hostname=bitcoind_Migration.embassy --no-healthcheck --mount type=bind,src=/embassy-data/package-data/volumes/bitcoind/data/main,dst=/root/.bitcoin --interactive --log-driver=journald --entrypoint /usr/local/bin/migrations/lt_22_0_0.sh start9/bitcoind/main:22.0.1 from", kill_on_drop: false }`

(Should be `eq_22_0_0.sh`, since we're coming from v22.0.0. It doesn't make sense to run `lt_22_0_0.sh` since that is the migration defined for versions *less than* v22.0.0.

5. Inspect the s9pk, just as a sanity check:

```
embassy-sdk inspect manifest bitcoind.s9pk | grep -C20 migrations
"migrations": {
    "from": {
      "<22.0.0": {
        "type": "docker",
        "image": "main",
        "system": false,
        "entrypoint": "/usr/local/bin/migrations/lt_22_0_0.sh",
        "args": [
          "from"
        ],
        "mounts": {
          "main": "/root/.bitcoin"
        },
        "io-format": "json",
        "inject": false,
        "shm-size-mb": null,
        "sigterm-timeout": null
      },
      "=22.0.0": {
        "type": "docker",
        "image": "main",
        "system": false,
        "entrypoint": "/usr/local/bin/migrations/eq_22_0_0.sh",
        "args": [
          "from"
        ],
        "mounts": {
          "main": "/root/.bitcoin"
        },
        "io-format": "json",
        "inject": false,
        "shm-size-mb": null,
        "sigterm-timeout": null
      }
    },
    "to": {
      "<22.0.0": {
        "type": "docker",
        "image": "main",
        "system": false,
        "entrypoint": "/usr/local/bin/migrations/lt_22_0_0.sh",
        "args": [
          "to"
        ],
        "mounts": {
          "main": "/root/.bitcoin"
        },
        "io-format": "json",
        "inject": false,
        "shm-size-mb": null,
        "sigterm-timeout": null
      },
      "=22.0.0": {
        "type": "docker",
        "image": "main",
        "system": false,
        "entrypoint": "/usr/local/bin/migrations/eq_22_0_0.sh",
        "args": [
          "to"
        ],
        "mounts": {
          "main": "/root/.bitcoin"
        },
        "io-format": "json",
        "inject": false,
        "shm-size-mb": null,
        "sigterm-timeout": null
      }
    }
  },
```
