### ISSUE TITLE
[feat]: Allow services to use HTTPS internally for .local

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/embassy-os#1525]
Steps to reproduce:

1) Install and run CLN
2) try to access <.local-address>:3001 (where the rest api is listening)
3) bad gateway:

<img width="721" alt="Screen Shot 2022-06-13 at 10 53 17 AM" src="https://user-images.githubusercontent.com/7445670/173394576-713f16b0-ea2a-4035-96c8-644fc9615782.png">

CLN lan config looks like: 
```
  rest:
    name: C-Lightning-REST API
    description: C-Lightning-REST is a plugin for Core Lightning written by the RTL team that exposes an LND-like REST API for C-Lightning.
    tor-config:
      port-mapping:
        3001: "3001"
    lan-config:
      3001:
        ssl: true
        internal: 3001
    ui: false
    protocols:
      - tcp
      - http
```
(see https://github.com/Start9Labs/c-lightning-wrapper/blob/357043734b7df0cf4c41ae5526d70ff9ea5dcf84/manifest.yaml#L116-L129 for whole config spec)

nginx config looks like:
```
server {
    listen 3001 ssl;
    listen [::]:3001 ssl;
    server_name .y4467stoyxis7d3ozuk42zxtglot4dtexctxvgbtsl6yt3vo3kgaycyd.local;
    ssl_certificate /etc/nginx/ssl/c-lightning/rest.cert.pem;
    ssl_certificate_key /etc/nginx/ssl/c-lightning/rest.key.pem;
    location / {
        proxy_pass http://172.18.0.3:3001/;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        client_max_body_size 0;
        proxy_request_buffering off;
        proxy_buffering off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }
}
```

I can `curl` the endpoint from on the embassy. No 502 here:
```
root@embassy-2ef08502:~# curl -k https://172.18.0.3:3001
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /</pre>
</body>
</html>
```

I can't figure out why this wouldn't work except for some kind of OS bug. 

Thoughts?
