### ISSUE TITLE
Service Migrations

### ISSUE THREAD

**Issue by KiaraStart9** [Start9Labs/embassy-os#286]
Done: app can specify and entry point to migrate application data from an old version and it will receive the old version as an argument
Effort: 2 days (Aiden)
Dependency: new manifest format (part of) (a part of the new manifest format that is decided and therefore has its own ticket)

**Comment by dr-bonez** [comment]
Assigning to @elvece for UAT

**Comment by elvece** [comment]
Working [example](https://github.com/Start9Labs/btcpayserver-wrapper/blob/integration/1.1.2.4/manifest.yaml#L33)

**Comment by chrisguida** [comment]
@dr-bonez @ProofOfKeags 

<img width="594" alt="Screen Shot 2021-12-06 at 12 10 40 PM" src="https://user-images.githubusercontent.com/7445670/144899265-f0ba13b5-43df-4b7f-92f1-d3f2f60a9392.png">

**Comment by dr-bonez** [comment]
Easiest way to cause an issue with config.get is to delete an option from an enum that is currently selected.

**Comment by chrisguida** [comment]
@dr-bonez Should we allow config data to simply be deleted like this when there's no migration? Shouldn't we at least store it under the old key like we used to in 02x?

**Comment by chrisguida** [comment]
Also, config.get is still not throwing an error even after I deleted a variant that i was using. But the frontend is bugging out with this:

<img width="835" alt="Screen Shot 2021-12-06 at 6 02 03 PM" src="https://user-images.githubusercontent.com/7445670/144942071-435ad4f3-654c-4949-a074-df008b54ff46.png">

**Comment by chrisguida** [comment]
It seems impossible to get config.get to throw an error on an incompatible config. This makes it hard to determine whether the migrations feature is working, because a migration is supposed to convert an incompatible config into a compatible one. @dr-bonez @ProofOfKeags @lucy please advise

**Comment by chrisguida** [comment]
Ok i tested with this migration per @dr-bonez's advice that exiting with a code other than 0 should cause installation to fail. Installation does not fail:

```
migrations:
  from:
    "<=0.1.1":
        type: docker
        image: main
        entrypoint: sh
        args: ["-c", 'exit 1']
        io-format: json
        inject: true
  to:
    "<=0.1.1":
        type: docker
        image: main
        entrypoint: sh
        args: ["-c", 'exit 1']
        io-format: json
        inject: true

```

**Comment by chrisguida** [comment]
Oh hang on, i just realized the versions are wrong..

**Comment by chrisguida** [comment]
Nope, nvm they were right.

Steps to reproduce:
1. install BAR 0.1.0 (need to hit "other versions")
2. configure with random inputs for "manual" enum variant
3. start/stop the service (can probably skip this)
4. update to BAR 0.1.1 (also not the latest version)
5. installation succeeds

**Comment by chrisguida** [comment]
here's the whole config_spec i'm using (not pushed for obvious reasons):

```
password:
  type: string
  name: Password
  nullable: false
  copyable: true
  masked: true
  default:
    len: 22
    charset: a-z,A-Z,0-9
connection-settings:
  type: union
  name: Connection Settings
  description: Information to connect to an external unpruned Bitcoin Core node
  tag:
    id: type
    name: Type
    description: |
      - Manual: Raw information for finding a Bitcoin Core node
      - Quick Connect: A Quick Connect URL for a Bitcoin Core node
    variant-names:
      manual: Manual
      quick-connect: Quick Connect
  default: quick-connect
  variants:
    manual:
      address:
        type: string
        name: Public Address
        description: The public address of your Bitcoin Core RPC server
        nullable: false
      user:
        type: string
        name: RPC Username
        description: The username for the RPC user on your Bitcoin Core RPC server
        nullable: false
      password:
        type: string
        name: RPC Password
        description: The password for the RPC user on your Bitcoin Core RPC server
        nullable: false
        masked: true
migrations:
  from:
    "<0.1.1":
        type: docker
        image: main
        entrypoint: sh
        args: ["-c", 'exit 1']
        io-format: json
        inject: true
  to:
    "<0.1.1":
        type: docker
        image: main
        entrypoint: sh
        args: ["-c", 'exit 1']
        io-format: json
        inject: true
```

**Comment by chrisguida** [comment]
changing `exit 1` to `'json=''{"configured": false }'' && echo "$json"'` also does not cause an installation failure

**Comment by chrisguida** [comment]
Wait, i'm dumb, this goes in the manifest xD

**Comment by chrisguida** [comment]
Ok even with it in the correct file, the migration is still not preventing an install. Not sure if I'm doing something else dumb.

Here's the 0.1.1 manifest:
```
id: burn-after-reading
title: "Burn After Reading"
version: 0.1.1 # cannot be 4 digits
release-notes: "Upgrade to EmbassyOS v0.3.0"
license: gnu
wrapper-repo: "https://github.com/Start9Labs/burn-after-reading"
upstream-repo: "https://github.com/Start9Labs/burn-after-reading"
support-site: "https://matrix.to/#/!lMnRwPWnyQvOfAoEnD:matrix.start9labs.com"
marketing-site: "https://start9.com"
build: ["make"]
min-os-version: "0.3.0"
description:
  short: Share messages and files that are destroyed after they are viewed
  long: |
    A simple, fast, standalone service that uses Tor (.onion) ephemeral links to share encrypted messages and files that are destroyed (burned) after they are viewed. Content is stored directly on the Embassy, and there are no trusted 3rd parties.
assets:
  license: LICENSE
  icon: icon.png
  instructions: instructions.md
  docker-images: image.tar
main:
  type: docker
  image: main
  entrypoint: tini
  args: ["/usr/local/bin/burn-after-reading"]
  mounts:
    main: /root
  io-format: yaml
health-checks:
  interface:
    name: Web Interface
    description: Ensures the network interface is accessible via HTTP.
    type: docker
    image: main
    entrypoint: sh
    args: ["-c", "curl burn-after-reading.embassy:80 || exit 1"]
    io-format: yaml
    severity: warning
    inject: true
config:
  get:
    type: docker
    image: compat
    system: true
    entrypoint: compat
    args: 
      - config
      - get
      - /root
      - "/mnt/assets/config_spec.yaml"
    mounts:
      compat: /mnt/assets
      main: /root
    io-format: yaml
  set:
    type: docker
    image: compat
    system: true
    entrypoint: compat
    args:
      - config
      - set
      - "burn-after-reading"
      - /root
      - "/mnt/assets/config_rules.yaml"
    mounts:
      compat: /mnt/assets
      main: /root
    io-format: yaml
properties:
  type: docker
  image: compat
  system: true
  entrypoint: compat
  args:
    - properties
    - /root
  mounts:
    main: /root
    compat: /mnt/assets
  io-format: yaml
dependencies: {}
volumes:
  main:
    type: data
  compat:
    type: assets
alerts: {}
interfaces:
  network:
    name: Network Interface
    description: Specifies the interfaces to listen on for HTTP connections.
    tor-config:
      port-mapping:
        80: "80"
    lan-config:
      80:
        ssl: true
        mapping: 443
    ui: true
    protocols:
      - tcp
      - http
backup:
  create:
    type: docker
    image: compat
    system: true
    entrypoint: compat
    args:
      - duplicity
      - create
      - /mnt/backup
      - /root/data
    mounts:
      BACKUP: /mnt/backup
      main: /root/data
    io-format: yaml
  restore:
    type: docker
    image: compat
    system: true
    entrypoint: compat
    args:
      - duplicity
      - restore
      - /mnt/backup
      - /root/data
    mounts:
      BACKUP: /mnt/backup
      main: /root/data
    io-format: yaml
migrations:
  from:
    "<0.1.1":
        type: docker
        image: main
        entrypoint: sh
        args: ["-c", 'exit 1']
        io-format: json
        inject: true
  to:
    "<0.1.1":
        type: docker
        image: main
        entrypoint: sh
        args: ["-c", 'exit 1']
        io-format: json
        inject: true
```
