### ISSUE TITLE
Change change-warning on all services to warning, and update health checks with name, description, and severity keys

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/embassy-os#832]
**Describe the bug**
I can't get change warnings to display on the FE

**To Reproduce**
- Install bitcoind
- hit "config"
- change any of the pruning settings. all of them have change warnings defined in the spec

**Expected behavior**
A change warning should pop up when toggling the variant between disabled, automatic, and manual variants. In addition, the change warnings on altering the pruning sizes 

**Actual behavior**
No warning appears

**Desktop (please complete the following information):**
 - OS and version: Ubuntu 20.04
 - Browser and version: FF 94.0

**Additional context**
here's the relevant portion of the bitcoind config spec:
```
    pruning:
      type: union
      name: "Pruning Settings"
      description: |
        Blockchain Pruning Options
        Reduce the blockchain size on disk
      change-warning: |
        If you set pruning to Manual and your disk is smaller than the total size of the blockchain, you MUST have something running that prunes these blocks or you may overfill your disk!
        Disabling pruning will convert your node into a full archival node. This requires a resync of the entire blockchain, a process that may take several days. Make sure you have enough free disk space or you may fill up your disk.
      tag:
        id: mode
        name: Pruning Mode
        description: |
          - Disabled: Disable pruning
          - Automatic: Limit blockchain size on disk to a certain number of megabytes
          - Manual: Prune blockchain with the "pruneblockchain" RPC
        variant-names:
          disabled: Disabled
          automatic: Automatic
          manual: Manual
      variants:
        disabled: {}
        automatic:
          size:
            type: number
            nullable: false
            name: "Max Chain Size"
            description: "Limit of blockchain size on disk."
            change-warning: "Increasing this value will require re-syncing your node."
            default: 550
            range: "[550,1000000)"
            integral: true
            units: MiB
        manual:
          size:
            type: number
            nullable: false
            name: "Failsafe Chain Size"
            description: "Prune blockchain if size expands beyond this."
            default: 65536
            range: "[550,1000000)"
            integral: true
            units: MiB
      default: disabled
```

git commit is `613b05788ba929679f62a03d34b15802ee4a5c37`, kind of old at this point
